builds:
- main: ./cmd/nfpm
  hooks:
    pre: packr
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
# dockers:
#   - image: goreleaser/nfpm
#     tag_templates:
#     - '{{ .Tag }}'
#     - 'v{{ .Major }}.{{ .Minor }}'
#     - 'latest'
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
brew:
  github:
    owner: goreleaser
    name: homebrew-tap
  folder: Formula
  homepage:  https://github.com/goreleaser/nfpm
  description: NFPM is not FPM
  test: |
    system "#{bin}/nfpm -v"
scoop:
  bucket:
    owner: goreleaser
    name: scoop-bucket
  homepage:  https://github.com/goreleaser/nfpm
  description: NFPM is not FPM
  license: MIT
# TODO: change to nfpm when released
# fpm:
#   name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
#   homepage:  https://github.com/goreleaser/nfpm
#   description: NFPM is not FPM
#   maintainer: Carlos Alexandro Becker <root@carlosbecker.com>
#   license: MIT
#   vendor: GoReleaser
#   formats:
#     - deb
#     - rpm
  # TODO: should be able to do that "suggested packages" thing
